### PR TITLE
conditionalUpdate

### PR DESCRIPTION
**Pull request by AurelieMerlo**
**Need**

We must make sure we do not create the same record multiple times. According to fhir documentation (https://www.hl7.org/fhir/http.html#cond-update), it's possible to using a conditional update that if it does not find record it creates it, if not it updates it.

**Problem**

Actually, the attribute `:id` is required when using `.update` which can not be provided in the case of a conditional update. 

**Solution**

I propose in this PR to add `.conditionalUpdate` which has the same behavior as `.search` but with a `PUT` method.

```
.conditionalUpdate({
    type: ${resourceType},
    data: ${patientPayload},
    query: {
      family: ${patientLastname},
      given: ${patientFirstname}
    }
  });
```

### CODE REVIEW

**Comment by pierrickouw** [comment]
@AurelieMerlo nice work, it will be very useful!
Could you add a small test for this feature?

**Comment by AurelieMerlo** [comment]
@pierrickouw @mike1pol 
Sorry, I forgot to add a test. I just added it

**Comment by pierrickouw** [comment]
Hi @mike1pol,
I am happy to help if you need someone to look at the review! 

Thanks

**Comment by mike1pol** [comment]
I think all ok.
@pierrickouw thx, if you think that everything is OK, approve and we will be merge

**Pull request merged**
