### PR TITLE
Fixing bug with typescript defns

### PR DESCRIPTION
**Pull request by joeldenning**
The closing parenthesis at the end of line 9 shouldn't be there -- it's invalid typescript.

image

### CODE REVIEW

**Comment by joeldenning** [comment]
The build failures seem to be unrelated to my code changes.

**Comment by fatmali** [comment]
Hi @joeldenning,there is a PR here also addressing the same https://github.com/FHIR/fhir.js/pull/143

**Comment by joeldenning** [comment]
Thanks for linking me to that, I didn't see it earlier. #143 makes changes to the source code, in addition to typescript changes. The PR description doesn't explain why those things have changed.

My PR here might be easier to merge since it's not making changes to the source code. I'll happily close in favor of #143 if the changes to the source code were intentional and mergeable.

**Comment by marrouchi** [comment]
Fixed in https://github.com/FHIR/fhir.js/pull/191

**Pull request closed without merging**
