### PR TITLE
Fix bugs related to Typescript data as well as Pagination

### PR DESCRIPTION
**Pull request by the-kenny**
`fhir.d.ts`:
* `Buffer` isn't a valid type on non-node platforms. Replace with `any`
* Invalid closing parenthesis on `ResourceName` enum

`fhir.js`:
* `$Pagination` injected its data into the wrong properties, effectively losing them

### CODE REVIEW

**Review by fatmali — CHANGES_REQUESTED** [review]
Hi @the-kenny, this PR is breaking tests specifically https://github.com/FHIR/fhir.js/blob/master/test/historySpec.coffee line 15 and 16, I guess you should change the tests from: 

```
assert.equal(q.params._count, 10)
assert.equal(q.params._since, '2000-01-01')
```
to:
```
 assert.equal(q.query._count, 10)
assert.equal(q.query._since, '2000-01-01')
```

Do you mind changing these? fhir.js v0.0.20 has dependency vulnerabilities and we'd like to upgrade to v0.0.23 but it cant compile due to the error with fhir.d.ts that you are fixing here :-)

**Comment by the-kenny** [comment]
@fatmali sure! I'll have a look in a minute

**Comment by the-kenny** [comment]
`all-tests` script is now green for me :-)

**Comment by fatmali** [comment]
@mike1pol could you help review this :-)

**Comment by fatmali** [comment]
Hi @mike1pol any feedback :-)

**Review by internettrans — COMMENTED** [review]
This PR says it's a typescript definitions change, but it also has changes to the source code? Is that on purpose? If so, what are the changes to the source code doing?

**Comment by the-kenny** [comment]
The title is unfortunate.  I’ll update it when I’ll arrive at the office later.

**Comment by fatmali** [comment]
Hi @mike1pol , any progress on this? :-)

**Comment by p1n5u** [comment]
@mike1pol @the-kenny any update on this? The TS definition update is really necessary as it provokes some build errors if used in for example an Vue.js App with typescript.

**Pull request closed without merging**
