### PR TITLE
removed repeated var declarations for better runtime performance

### PR DESCRIPTION
**Pull request by aspencerpsu**
Please review my proposed changes, you can skim 10-15 ms of performance for the fhir adapter methods

### CODE REVIEW

**Comment by niquola** [comment]
Does it really affect performance, how do you measure? :)

**Comment by aspencerpsu** [comment]
Sorry, I didn't take a screenshot of the test evaluations. But on my raspberry pi, I noticed some subtle differences in the completion times for each of the tests.

I run the mocha compiler test a few times, but I didn't capture an average performance speed for the tests. 

I figured the less variable declarations, the optimization of the runtime would improve, but waking up this morning, I may reject that supposition.

You can dispose of the incessant var declarations and then minify the fhir adapters and middleware functions for better performance in my opinion. But let me know your thoughts on this type of quality inspection and test.

--Akeem Spencer

**Comment by mike1pol** [comment]
This does not affect performance.

**Comment by aspencerpsu** [comment]
I disagree, I was able to skim some ms on the build.

And to add to this thread, shouldn't `var` declarations be replaced with `let` or `const` declarations for ES6/ES5 conformity?

**Comment by RangerMauve** [comment]
If you want the performance benefits of something like this, it'd be better to bundle all the code into a single file and then run that through a minifier like [Uglify](https://github.com/mishoo/UglifyJS).

That way you can keep the source code pretty and have a bunch of these changes performed automatically.

**Pull request closed without merging**
